### ISSUE TITLE
启动的时候报错了

### ISSUE THREAD

**Issue by wangzhigang** [zhanyuzhang/deno-supermarket#1]
start successfully. you can visit it on http://localhost:8000/pages/
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ServerSelectionError { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: Unknown, Error: Connection refused (os error 61) }, ] }" } }', src/command/find.rs:41:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by zhanyuzhang** [comment]
@wangzhigang 你电脑要先安装并且启动 mongodb 。另外它的默认端口 27017 ，如果你修改过 mongodb 端口，也要在config/db.ts 里修改一下。

**Comment by wangzhigang** [comment]
mongodb 已经启动了...奇怪了..不知道为啥链接不上...

**Comment by wangzhigang** [comment]
找到原因了..host呗修改了
